// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY8zPZW14w7zC9SzWTsyWg9uKU7isSBnQ',
    appId: '1:378327992581:web:107b477dc22c49152b8f6c',
    messagingSenderId: '378327992581',
    projectId: 'passwardmaneger',
    authDomain: 'passwardmaneger.firebaseapp.com',
    storageBucket: 'passwardmaneger.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCQiSmawgCrUUx8YW1S2RbhMCNUTDJzrE',
    appId: '1:378327992581:android:b8f25989c15b47952b8f6c',
    messagingSenderId: '378327992581',
    projectId: 'passwardmaneger',
    storageBucket: 'passwardmaneger.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUH_BCM5YyyuTB1CqN2wrF0ta_OYGqsOs',
    appId: '1:378327992581:ios:fc40f1ecfbe839af2b8f6c',
    messagingSenderId: '378327992581',
    projectId: 'passwardmaneger',
    storageBucket: 'passwardmaneger.appspot.com',
    iosBundleId: 'com.example.passwordmanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY8zPZW14w7zC9SzWTsyWg9uKU7isSBnQ',
    appId: '1:378327992581:web:519c9afdae9eadc12b8f6c',
    messagingSenderId: '378327992581',
    projectId: 'passwardmaneger',
    authDomain: 'passwardmaneger.firebaseapp.com',
    storageBucket: 'passwardmaneger.appspot.com',
  );
}
